package MyLibrary;

import java.awt.event.KeyEvent;
import java.util.StringTokenizer;

/**
 * Displays Book information to be viewed by the user.
 * @author Bryan Fulton
 */
public class InfoPanel extends javax.swing.JPanel {
    private LibraryFrame frame;
    private String       title,
                         author,
                         publisher,
                         publicationDate,
                         isbn,
                         description,
                         type;
    /**
     * Creates a new InfoPanel.
     * @param frame The frame containing this Panel.
     */
    public InfoPanel(LibraryFrame frame) {
        initComponents();
        this.frame = frame;
    }
    
    /**
     * Populates the Panel's fields withe the Book's data.
     * @param str The String representation of a Book object.
     */
    public void displayData(String str) {
        StringTokenizer tokens = new StringTokenizer(str, "<>");
        
        title = tokens.nextToken();
        author = tokens.nextToken();
        publisher = tokens.nextToken();
        publicationDate = tokens.nextToken();
        isbn = tokens.nextToken();
        description = tokens.nextToken();
        type = tokens.nextToken();
        
        titleTextField.setText(title);
        authorTextField.setText(author);
        publisherTextField.setText(publisher);
        publicationYearTextField.setText(publicationDate);
        isbnTextField.setText(isbn);
        descriptionTextArea.setText(description);
        curTypeLabel.setText(type);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldsPanel = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        publicationYearLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        publicationYearTextField = new javax.swing.JTextField();
        publisherTextField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        isbnTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        authorTextField = new javax.swing.JTextField();
        closeButtonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        typePanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        curTypeLabel = new javax.swing.JLabel();

        fieldsPanel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        instructionLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        instructionLabel.setText("Review the following information at your desire. Hit the back button to return to the browse screen.");

        titleLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        titleLabel1.setText("Title:");

        authorLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        authorLabel.setText("Author:");

        publisherLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        publisherLabel.setText("Publisher:");

        publicationYearLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        publicationYearLabel.setText("Publication Year:");

        isbnLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        isbnLabel.setText("ISBN:");

        descriptionLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        descriptionLabel.setText("Description:");

        publicationYearTextField.setEditable(false);
        publicationYearTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        publisherTextField.setEditable(false);
        publisherTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        titleTextField.setEditable(false);
        titleTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        isbnTextField.setEditable(false);
        isbnTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setEditable(false);
        descriptionTextArea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionTextArea);

        authorTextField.setEditable(false);
        authorTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout fieldsPanelLayout = new javax.swing.GroupLayout(fieldsPanel);
        fieldsPanel.setLayout(fieldsPanelLayout);
        fieldsPanelLayout.setHorizontalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(publisherLabel)
                        .addGap(51, 51, 51)
                        .addComponent(publisherTextField))
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(publicationYearLabel)
                        .addGap(18, 18, 18)
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publicationYearTextField)
                            .addComponent(isbnTextField)
                            .addComponent(jScrollPane1)))
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel1)
                        .addGap(73, 73, 73)
                        .addComponent(titleTextField))
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instructionLabel)
                            .addComponent(isbnLabel)
                            .addComponent(descriptionLabel))
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addGroup(fieldsPanelLayout.createSequentialGroup()
                        .addComponent(authorLabel)
                        .addGap(61, 61, 61)
                        .addComponent(authorTextField)))
                .addContainerGap())
        );
        fieldsPanelLayout.setVerticalGroup(
            fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel1)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicationYearLabel)
                    .addComponent(publicationYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel)
                    .addComponent(isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setMnemonic(KeyEvent.VK_B);
        backButton.setText("<html><u>B</u>ack");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        modifyButton.setMnemonic(KeyEvent.VK_M);
        modifyButton.setText("<html><u>M</u>odify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout closeButtonPanelLayout = new javax.swing.GroupLayout(closeButtonPanel);
        closeButtonPanel.setLayout(closeButtonPanelLayout);
        closeButtonPanelLayout.setHorizontalGroup(
            closeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        closeButtonPanelLayout.setVerticalGroup(
            closeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closeButtonPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(closeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        typePanel.setLayout(new java.awt.GridLayout(2, 1));

        typeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Book Type: ");
        typePanel.add(typeLabel);

        curTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        curTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curTypeLabel.setText("Fiction");
        typePanel.add(curTypeLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(fieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sends user back to the Browse screen.
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        frame.showPanel(LibraryConstants.BROWSE);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * Sends Book information out to be modified.
     * @param evt 
     */
    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        String[] allStrings = {title, author, publisher, publicationDate,
            isbn, description, type};
        frame.modify(allStrings);
    }//GEN-LAST:event_modifyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel closeButtonPanel;
    private javax.swing.JLabel curTypeLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel publicationYearLabel;
    private javax.swing.JTextField publicationYearTextField;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField publisherTextField;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel typePanel;
    // End of variables declaration//GEN-END:variables
 
}
